from pathlib import Path

MASK = (1 << 64) - 1
FNV_OFFSET = 1469598103934665603
FNV_PRIME = 1099511628211
PHRASES = [
    b"Libertas per Croack!",
    b"Presunto",
    b"Floquinha",
    b"In Frog we Trust!",
]
AES = [
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
    0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
    0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
    0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
    0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
    0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
    0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
    0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
    0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
    0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
    0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16,
]


def rotl(x, n):
    n &= 63
    return x if n == 0 else ((x << n) | (x >> (64 - n))) & MASK


def fnv(domain, phrase, counter):
    h = FNV_OFFSET
    for b in domain:
        h ^= b
        h = (h * FNV_PRIME) & MASK
    h ^= 0
    h = (h * FNV_PRIME) & MASK
    for b in phrase:
        h ^= b
        h = (h * FNV_PRIME) & MASK
    for i in range(8):
        h ^= (counter >> (8 * i)) & 0xFF
        h = (h * FNV_PRIME) & MASK
    return h


def splitmix(state):
    state = (state + 0x9E3779B97F4A7C15) & MASK
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return state, (z ^ (z >> 31)) & MASK


def bitperm(x, p):
    y = 0
    for out in range(8):
        y |= ((x >> p[out]) & 1) << out
    return y


def random_perm(state):
    p = list(range(8))
    for i in range(7, 0, -1):
        state, z = splitmix(state)
        j = z % (i + 1)
        p[i], p[j] = p[j], p[i]
    return state, p


def forbidden(box):
    return any(y == x or y == (x ^ 0xFF) for x, y in enumerate(box))


def derive_sbox(index):
    counter = 0
    while True:
        state = fnv(b"FrogBard-512/SBOX/v1", PHRASES[index], counter)
        state, pin = random_perm(state)
        state, pout = random_perm(state)
        state, z = splitmix(state)
        inxor = z & 0xFF
        state, z = splitmix(state)
        outxor = z & 0xFF
        box = []
        for x in range(256):
            a = bitperm(x ^ inxor, pin)
            b = AES[a]
            box.append(bitperm(b, pout) ^ outxor)
        if not forbidden(box):
            inv = [0] * 256
            for x, y in enumerate(box):
                inv[y] = x
            return {
                "box": box,
                "inv": inv,
                "pin": pin,
                "pout": pout,
                "inxor": inxor,
                "outxor": outxor,
                "counter": counter,
            }
        counter += 1


sbox_meta = [derive_sbox(i) for i in range(4)]
sboxes = [m["box"] for m in sbox_meta]

seed = 0x46524F4742415244
for p in range(4):
    seed ^= fnv(b"FrogBard-512/ROUND-CONSTANTS/v1", PHRASES[p], p)
    seed, z = splitmix(seed)
    seed = z

rc = []
for r in range(16):
    rv = []
    for voice in range(4):
        vv = []
        for lane in range(8):
            seed, x = splitmix(seed)
            x ^= (0x9E3779B97F4A7C15 * (1 + r)) & MASK
            x ^= rotl((0xD1B54A32D192ED03 * (1 + voice)) & MASK, lane + 1)
            vv.append(x & MASK)
        rv.append(vv)
    rc.append(rv)

out = []
out.append("/* Auto-generated by tools/gen_tables.py. Do not edit manually. */")
out.append("#ifndef FROGBARD_TABLES_H")
out.append("#define FROGBARD_TABLES_H")
out.append("")

for name, boxes in (("FROGBARD_SBOX", [m["box"] for m in sbox_meta]),
                    ("FROGBARD_SBOX_INV", [m["inv"] for m in sbox_meta])):
    out.append(f"static const alignas(64) uint8_t {name}[4][256] = {{")
    for box in boxes:
        out.append("    {")
        for i in range(0, 256, 16):
            out.append("        " + ",".join(f"0x{x:02x}" for x in box[i:i + 16]) + ",")
        out.append("    },")
    out.append("};\n")

out.append("static const uint8_t FROGBARD_SBOX_PIN[4][8] = {")
for m in sbox_meta:
    out.append("    {" + ", ".join(str(x) for x in m["pin"]) + "},")
out.append("};")
out.append("static const uint8_t FROGBARD_SBOX_POUT[4][8] = {")
for m in sbox_meta:
    out.append("    {" + ", ".join(str(x) for x in m["pout"]) + "},")
out.append("};")
out.append("static const uint8_t FROGBARD_SBOX_IN_XOR[4] = {" + ", ".join(f"0x{m['inxor']:02x}" for m in sbox_meta) + "};")
out.append("static const uint8_t FROGBARD_SBOX_OUT_XOR[4] = {" + ", ".join(f"0x{m['outxor']:02x}" for m in sbox_meta) + "};")
out.append("static const uint8_t FROGBARD_SBOX_COUNTER[4] = {" + ", ".join(str(m["counter"]) for m in sbox_meta) + "};\n")

out.append("static const alignas(64) uint64_t FROGBARD_RC[FROGBARD_ROUNDS][4][8] = {")
for r in rc:
    out.append("    {")
    for v in r:
        out.append("        {" + ", ".join(f"UINT64_C(0x{x:016x})" for x in v) + "},")
    out.append("    },")
out.append("};\n")

iv = []
for voice in range(4):
    state = fnv(b"FrogBard-512/IV/v1", PHRASES[voice], voice)
    lanes = []
    for lane in range(8):
        state, z = splitmix(state)
        value = z ^ rc[0][voice][lane] ^ rotl(0x46524F4742415244, lane * 7 + voice)
        lanes.append(value & MASK)
    iv.append(lanes)
out.append("static const alignas(64) uint64_t FROGBARD_IV[4][8] = {")
for v in iv:
    out.append("    {" + ", ".join(f"UINT64_C(0x{x:016x})" for x in v) + "},")
out.append("};\n")
out.append("#endif")

path = Path(__file__).resolve().parent.parent / "src" / "frogbard_tables.h"
path.write_text("\n".join(out) + "\n")
print("generated", path, "bytes", path.stat().st_size)
for i, m in enumerate(sbox_meta):
    print(i, PHRASES[i].decode(), "counter", m["counter"], "pin", m["pin"], "pout", m["pout"],
          "inxor", hex(m["inxor"]), "outxor", hex(m["outxor"]))
